WITH inp_all AS (
    SELECT DSYSRTKY, ADMSN_DT, PRNCPAL_DGNS_CD FROM INP_claimsk_2017
    UNION ALL SELECT DSYSRTKY, ADMSN_DT, PRNCPAL_DGNS_CD FROM inp_claimsk_2018
    UNION ALL SELECT DSYSRTKY, ADMSN_DT, PRNCPAL_DGNS_CD FROM inp_claimsk_2019
    UNION ALL SELECT DSYSRTKY, ADMSN_DT, PRNCPAL_DGNS_CD FROM inp_claimsk_2020
    UNION ALL SELECT DSYSRTKY, ADMSN_DT, PRNCPAL_DGNS_CD FROM INP_claimsk_2021
    UNION ALL SELECT DSYSRTKY, ADMSN_DT, PRNCPAL_DGNS_CD FROM INP_claimsk_2022
    UNION ALL SELECT DSYSRTKY, ADMSN_DT, PRNCPAL_DGNS_CD FROM inp_claimsk_2023
)
SELECT i.PRNCPAL_DGNS_CD,
       COUNT(*) AS n,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 1) AS pct
FROM inp_all i
JOIN io_analytic a ON i.DSYSRTKY = a.DSYSRTKY
WHERE TRY_STRPTIME(i.ADMSN_DT, '%Y%m%d') BETWEEN (a.death_dt - INTERVAL 30 DAY) AND a.death_dt
  AND i.PRNCPAL_DGNS_CD IS NOT NULL
  AND i.PRNCPAL_DGNS_CD <> ''
GROUP BY i.PRNCPAL_DGNS_CD
ORDER BY n DESC
LIMIT 10;
